import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { Lato } from "next/font/google";
import { Header } from "@/components/shared";

const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: ["100", "300", "400"],
});
export const metadata: Metadata = {
  title: "Main Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.variable}>
        <Header />
        <main className="min-h-screen bg-white"> {children}</main>
      </body>
    </html>
  );
}
